export const PIZZA_VIEWED = "PIZZA_VIEWED";
export const PIZZA_SELECTED = "PIZZA_SELECTED";
export const PIZZA_ADDED_INTO_BASKET = "PIZZA_ADDED_INTO_BASKET";
export const PIZZA_REMOVED_FROM_BASKET = "PIZZA_REMOVED_FROM_BASKET";
export const LOAD_ITEMS = "LOAD_ITEMS";
